server:
  port: 8088
spring:
  application:
    name: cart-service
  redis:
    host: 106.54.86.212
    password: 123456
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 10
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
leyou:
  jwt:
    pubKeyPath: /Users/xu7777777/profile/key/rsa.pub # 公钥地址
    cookieName: LY_TOKEN_ # cookie的名称