server:
  port: 8081
spring:
  rabbitmq:
    host: 106.54.86.212
    username: leyou
    password: leyou
    virtual-host: /leyou
    template:
      exchange: leyou.item.exchange
    publisher-confirms: true
  application:
    name: item-service
  datasource:
    url: jdbc:mysql://106.54.86.212/heima?characterEncoding=utf-8
    username: root
    password: xqy666
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
#    register-with-eureka: false
#    fetch-registry: false
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 30
mybatis:
  type-aliases-package: com.leyou.item.pojo
